// derive-notice.mjs — NOTICE is DERIVED from the tree it describes, never copied between
// trees (the dev repository and the distributable tree ship different third-party material:
// the download tree carries a llama.cpp build and a Node runtime, the repository carries
// the website fonts and the benchmark corpus). Every line names files that exist; every
// third-party-looking file has a line. Either failing fails the run.
//
//   node tools/derive-notice.mjs [--root <dir>] [--write] [--deps] [--webui <llama.cpp checkout>]
//
// check (default): derive NOTICE for the tree at --root (this repository when omitted),
//   compare it with the NOTICE on disk, check every path THIRD_PARTY_NOTICES.md names and
//   the counts it states, check that the installer configuration still carries the notices
//   and licenses/ (whose files must match licenses/README.md's sha256 list) and that its
//   licence page is LICENSE byte for byte followed by the section on Microsoft's files in
//   the llama folder (with CONTROLs that must fail), and exit 1 on any difference or any
//   unaccounted file.
// --write: write the derived NOTICE, then run the same checks.
// --deps: first rewrite licenses/rust-crates.txt and licenses/npm-packages.txt (the licence
//   texts of the crates and npm packages the app is compiled from) and their sha256 in
//   licenses/README.md. Needs cargo and app/frontend/node_modules; a check does not.
// --webui <dir>: first rewrite licenses/llama.cpp-webui-npm-packages.txt, the licence texts
//   of the npm packages in the web page llama-server.exe carries, and its sha256 in
//   licenses/README.md. <dir> is a llama.cpp checkout at the commit llama-cuda/ was built
//   from, with `npm ci` run in its tools/ui. The run builds that page with the checkout's own
//   configuration, fails unless each built file occurs whole in llama-cuda/llama-server.exe,
//   and lists every package the build kept code from or read a style or font file from.
//
// The inventory is `git ls-files` (tracked, plus untracked files git does not ignore: what a
// commit of this working tree would carry) when the root is a git checkout — a clone is what
// the repository's NOTICE describes, so files on disk that are gitignored (the llama.cpp
// build in llama-cuda/, the Node sidecar, OCR language data) do not count — and a walk of
// the disk otherwise (the distributable tree has no git; what is there ships).
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const args = process.argv.slice(2);
const flag = (n) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : null; };
const ROOT = resolve(flag('--root') || join(dirname(fileURLToPath(import.meta.url)), '..'));
const WRITE = args.includes('--write');
const DEPS = args.includes('--deps');
const isGit = existsSync(join(ROOT, '.git'));

// ── the licence texts of the code compiled into the app (--deps writes them) ─────────
// The app's executable links Rust crates, and the window's bundle carries npm packages. Their
// licence texts go in licenses/ with the rest of what the installer carries. --deps rewrites
// the two files from `cargo metadata` (needs cargo and the crates in its local registry) and
// app/frontend/node_modules (needs `npm ci` there); a check reads only the lockfiles, so it
// runs anywhere and fails when a lockfile has changed since the files were written.
const DEP = {
  rust: { file: 'licenses/rust-crates.txt', lock: 'app/src-tauri/Cargo.lock', kind: 'crate' },
  npm: { file: 'licenses/npm-packages.txt', lock: 'app/frontend/package-lock.json', kind: 'package' },
};
const LICENSE_NAME = /^(licen[cs]es?|copying|notice|unlicense|copyright)([-._].*)?$/i;
const hashText = (t) => createHash('sha256').update(t).digest('hex');
function licenceTexts(dir) {
  const out = [];
  for (const n of readdirSync(dir).sort()) {
    if (!LICENSE_NAME.test(n)) continue;
    const p = join(dir, n);
    if (statSync(p).isFile()) out.push([n, readFileSync(p, 'utf8').replace(/\r\n/g, '\n')]);
    else for (const m of readdirSync(p).sort()) if (statSync(join(p, m)).isFile()) out.push([`${n}/${m}`, readFileSync(join(p, m), 'utf8').replace(/\r\n/g, '\n')]);
  }
  return out;
}
const lockLine = (key) => `Generated by \`node tools/derive-notice.mjs --deps\` from ${DEP[key].lock}\n(sha256 ${createHash('sha256').update(readFileSync(join(ROOT, DEP[key].lock))).digest('hex')}). Line endings are\nwritten as LF; the words are the files' own.`;
// licenses/README.md records each file's sha256 in its table; rewrite the row of each file named
function recordSha(names, why) {
  const readmePath = join(ROOT, 'licenses', 'README.md');
  let readme = readFileSync(readmePath, 'utf8');
  for (const name of names) {
    const h = createHash('sha256').update(readFileSync(join(ROOT, 'licenses', name))).digest('hex');
    const next = readme.replace(new RegExp('^(\\| `' + name.replace(/[.]/g, '\\.') + '` \\|.*\\| `)[0-9a-f]{64}(` \\|\\s*)$', 'm'), `$1${h}$2`);
    if (next === readme && !readme.includes(h)) { console.error(`${why}: licenses/README.md has no row for ${name}`); process.exit(2); }
    readme = next;
  }
  writeFileSync(readmePath, readme);
}
function renderDeps(kind, title, intro, items, generated) {
  const texts = new Map();
  const rows = items.map((it) => {
    const refs = it.texts.map(([file, text]) => {
      const h = hashText(text);
      if (!texts.has(h)) texts.set(h, { id: `T${String(texts.size + 1).padStart(3, '0')}`, text, users: [] });
      const t = texts.get(h);
      t.users.push(`${it.name} ${it.version} (${file})`);
      return `${t.id} ${file}`;
    });
    return `${kind} ${it.name} ${it.version}  [${it.license || 'no licence field'}]  ${refs.length ? refs.join(', ') : `no licence file in the published ${kind}${it.repository ? `; source: ${it.repository}` : ''}${it.authors ? `; authors: ${it.authors}` : ''}`}${it.note ? `\n    (${it.note})` : ''}`;
  });
  const bar = (s, c) => c.repeat(s.length);
  return `${title}\n${bar(title, '=')}\n\n${intro}\n\n${generated}\n\n${items.length} ${kind}s, ${texts.size} distinct licence texts.\n\n${rows.join('\n')}\n\n${[...texts.values()].map((t) => `${'-'.repeat(78)}\n${t.id}, the text of: ${t.users.join('; ')}\n${'-'.repeat(78)}\n\n${t.text.replace(/\s+$/, '')}\n`).join('\n')}`;
}
// Crates that carry prebuilt binaries. A crate whose package holds a .lib, .dll, .a, .o, .obj
// or .exe must be named here, or --deps fails: what such a file links into the app is not the
// crate's own source and its licence is not the crate's. windows_x86_64_msvc carries import
// libraries only (the names of Windows' own DLL functions, no code). webview2-com-sys carries
// Microsoft's WebView2 loader, and its build links WebView2LoaderStatic.lib into the app; the
// sha256 is that file's in the NuGet package the licence was copied from.
const PREBUILT = {
  windows_x86_64_msvc: { files: /^lib\/windows\.[0-9.]+\.lib$/ },
  'webview2-com-sys': {
    files: /^(x64|x86|arm64)[\\/](WebView2Loader\.dll|WebView2Loader\.dll\.lib|WebView2LoaderStatic\.lib)$/,
    linked: 'x64/WebView2LoaderStatic.lib', sha256: '0659b741bde6348d4c4a6ec4ceb9af50e3d0048ed9cd3c8659bccbb61fde55ee',
    note: "its build links x64/WebView2LoaderStatic.lib, Microsoft's WebView2 loader from the NuGet\n    package Microsoft.Web.WebView2 1.0.3650.58, into the app's executable; that\n    library's licence is licenses/Microsoft.Web.WebView2-LICENSE.txt, and the\n    package's notices file is licenses/Microsoft.Web.WebView2-NOTICE.txt",
  },
};
const binariesIn = (dir, rel = '') => readdirSync(join(dir, rel)).flatMap((n) => {
  const r = rel ? `${rel}/${n}` : n;
  return statSync(join(dir, r)).isDirectory() ? binariesIn(dir, r) : /\.(lib|dll|a|o|obj|exe)$/i.test(n) ? [r] : [];
});
if (DEPS) {
  // Rust: what the app's executable links, for the target the installer is built for. Normal
  // dependencies only, followed from the app; a procedural macro runs at compile time and is
  // not linked, so neither it nor what it depends on is listed.
  const meta = (() => {
    const run = (extra) => execFileSync('cargo', ['metadata', '--format-version', '1', '--locked', ...extra, '--filter-platform', 'x86_64-pc-windows-msvc'], { cwd: join(ROOT, 'app', 'src-tauri'), encoding: 'utf8', maxBuffer: 1 << 28, stdio: ['ignore', 'pipe', 'inherit'] });
    try { return JSON.parse(run(['--offline'])); } catch { return JSON.parse(run([])); }
  })();
  const byId = new Map(meta.packages.map((p) => [p.id, p]));
  const nodes = new Map(meta.resolve.nodes.map((n) => [n.id, n]));
  const procMacro = (p) => p.targets.some((t) => t.kind.includes('proc-macro'));
  const seen = new Set();
  for (const stack = [meta.resolve.root]; stack.length;) {
    const id = stack.pop();
    if (seen.has(id)) continue;
    seen.add(id);
    if (id !== meta.resolve.root && procMacro(byId.get(id))) continue;
    for (const d of nodes.get(id).deps) if (d.dep_kinds.some((k) => k.kind === null)) stack.push(d.pkg);
  }
  seen.delete(meta.resolve.root);
  const crates = [...seen].map((id) => byId.get(id)).filter((p) => !procMacro(p))
    .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version))
    .map((p) => {
      const dir = dirname(p.manifest_path);
      const bins = binariesIn(dir);
      const pb = PREBUILT[p.name];
      const stray = bins.filter((b) => !pb || !pb.files.test(b));
      if (stray.length) { console.error(`--deps: crate ${p.name} ${p.version} carries prebuilt ${stray.join(', ')}; say in PREBUILT (tools/derive-notice.mjs) what it links and under which licence`); process.exit(2); }
      if (pb?.linked) {
        const h = createHash('sha256').update(readFileSync(join(dir, pb.linked))).digest('hex');
        if (h !== pb.sha256) { console.error(`--deps: ${p.name} ${p.version} carries a ${pb.linked} with sha256 ${h}, not the ${pb.sha256} whose licence licenses/ holds`); process.exit(2); }
      }
      return { name: p.name, version: p.version, license: p.license, repository: p.repository, authors: (p.authors || []).join(', '), texts: licenceTexts(dir), note: pb?.note };
    });
  writeFileSync(join(ROOT, DEP.rust.file), renderDeps('crate', "Rust crates linked into the app's executable",
    `Every crate the app's executable links when built for x86_64-pc-windows-msvc,\nas \`cargo metadata --locked --filter-platform x86_64-pc-windows-msvc\` in\napp/src-tauri resolves it: the app's normal dependencies, followed from the app.\nProcedural macros and build-time dependencies run while compiling and are not\nlinked, so they are not listed. Each line gives the crate's name, version and\nthe licence expression its Cargo.toml states, then the licence files its\npublished package carries, by the number of the text below. Where a crate\noffers a choice of licences, every text it ships is given. A crate that links\na prebuilt library says so on the line below its own. The Rust standard\nlibrary is also linked. Its copyright file, share/doc/rust/COPYRIGHT-library.html\nin every Rust toolchain, says it is licensed under Apache-2.0 or MIT "except as\notherwise noted"; that file is not reproduced here.`, crates, lockLine('rust')));
  // npm: every package app/frontend's lockfile installs for production (not a dev tool, not an
  // optional platform binary). The window's bundle is built from these; listing a package the
  // bundler then leaves out costs a few lines, and missing one would cost its notice.
  const lockJson = JSON.parse(readFileSync(join(ROOT, DEP.npm.lock), 'utf8'));
  const pkgs = Object.entries(lockJson.packages).filter(([k, v]) => k && !v.dev && !v.devOptional && !v.optional)
    .map(([k, v]) => {
      const dir = join(ROOT, 'app', 'frontend', k);
      if (!existsSync(dir)) { console.error(`--deps: ${k} is not installed under app/frontend (run npm ci there first)`); process.exit(2); }
      const pj = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
      return { name: k.replace(/^.*node_modules\//, ''), version: v.version, license: v.license || pj.license, repository: typeof pj.repository === 'string' ? pj.repository : pj.repository?.url, authors: typeof pj.author === 'string' ? pj.author : pj.author?.name, texts: licenceTexts(dir) };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
  // The bundler is a development dependency, but its build adds modules of its own to the
  // window's code: a scratch build of app/frontend on 2026-09-25 carried vite's module-preload
  // polyfill and the CommonJS helpers of the plug-in vite bundles. So vite is listed too.
  const viteDir = join(ROOT, 'app', 'frontend', 'node_modules', 'vite');
  if (!existsSync(viteDir)) { console.error('--deps: vite is not installed under app/frontend (run npm ci there first)'); process.exit(2); }
  const vitePj = JSON.parse(readFileSync(join(viteDir, 'package.json'), 'utf8'));
  pkgs.push({ name: 'vite', version: vitePj.version, license: vitePj.license, texts: licenceTexts(viteDir), note: "the bundler, a development dependency: listed because its build adds modules of\n    its own to the window's code, a module-preload polyfill and CommonJS helpers" });
  pkgs.sort((a, b) => a.name.localeCompare(b.name));
  writeFileSync(join(ROOT, DEP.npm.file), renderDeps('package', 'npm packages in the app window\'s bundle',
    `Every package app/frontend/package-lock.json installs for production (not a\ndevelopment tool, not an optional platform binary), and the bundler. The\nwindow's code is bundled from these. Each line gives the package's name,\nversion and licence field, then the licence files it ships, by the number of\nthe text below.`, pkgs, lockLine('npm')));
  recordSha(Object.values(DEP).map(({ file }) => file.slice('licenses/'.length)), '--deps');
  console.log(`--deps: wrote ${DEP.rust.file} (${crates.length} crates) and ${DEP.npm.file} (${pkgs.length} packages)`);
}

// ── the web page llama-server.exe carries (--webui writes its licence file) ───────
// llama-server.exe embeds a web page (index.html, bundle.js, bundle.css, loading.html) built
// by vite from npm packages in llama.cpp's tools/ui. None of their licences is among the texts
// llama.cpp's build embeds, so --webui rebuilds the page from a checkout, proves the build is
// the one that ships (each file occurs whole in the server), and lists what the build used.
const WEBUI = { file: 'licenses/llama.cpp-webui-npm-packages.txt', exe: 'llama-cuda/llama-server.exe', parts: ['index.html', 'bundle.js', 'bundle.css', 'loading.html'] };
const WEBUI_CONFIG = `// Written by simpler-legal's tools/derive-notice.mjs --webui for one build and deleted after
// it: this checkout's own vite.config.ts plus one plugin that records, for every output file,
// the modules rollup kept in it and how many bytes of each survived, and the files the build read.
import base from './vite.config';
import { mergeConfig } from 'vite';
import { appendFileSync } from 'fs';

export default async (env: any) => mergeConfig(typeof base === 'function' ? await (base as any)(env) : base, {
	plugins: [{
		name: 'derive-notice:list-modules',
		apply: 'build',
		generateBundle(_opts: any, bundle: any) {
			const out: Record<string, unknown> = {};
			for (const [file, c] of Object.entries<any>(bundle)) out[file] = c.type === 'chunk' ? Object.fromEntries(Object.entries<any>(c.modules).map(([id, m]) => [id, m.renderedLength])) : null;
			appendFileSync(process.env.DERIVE_NOTICE_LIST as string, JSON.stringify({ ssr: !!(this as any).environment?.config?.build?.ssr, out, watch: (this as any).getWatchFiles() }) + '\\n');
		}
	}]
});
`;
if (flag('--webui')) {
  const die = (m) => { console.error(`--webui: ${m}`); process.exit(2); };
  const co = resolve(flag('--webui'));
  const ui = join(co, 'tools', 'ui');
  const viteBin = join(ui, 'node_modules', 'vite', 'bin', 'vite.js');
  if (!existsSync(join(ui, 'vite.config.ts'))) die(`${ui} has no vite.config.ts; pass a llama.cpp checkout`);
  if (!existsSync(viteBin)) die(`vite is not installed under ${ui} (run npm ci there first)`);
  const exePath = join(ROOT, WEBUI.exe);
  if (!existsSync(exePath)) die(`${WEBUI.exe} is missing; the page is checked against the server that ships`);
  const commit = execFileSync('git', ['-C', co, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
  const dist = join(co, 'build', 'tools', 'ui', 'dist'); // svelte.config.js and the checkout's build plug-in write here
  const listPath = join(ui, '.derive-notice-modules.jsonl');
  const confPath = join(ui, 'vite.derive-notice.config.ts');
  rmSync(dist, { recursive: true, force: true });
  rmSync(listPath, { force: true });
  writeFileSync(confPath, WEBUI_CONFIG);
  let r;
  try { r = spawnSync(process.execPath, [viteBin, 'build', '--config', confPath], { cwd: ui, encoding: 'utf8', maxBuffer: 1 << 28, env: { ...process.env, DERIVE_NOTICE_LIST: listPath } }); }
  finally { rmSync(confPath, { force: true }); }
  if (r.status !== 0) die(`the build failed (exit ${r.status}):\n${(r.stdout + r.stderr).slice(-3000)}`);
  const exe = readFileSync(exePath);
  for (const p of WEBUI.parts) {
    if (!existsSync(join(dist, p))) die(`the build wrote no ${p} to ${dist}`);
    if (exe.indexOf(readFileSync(join(dist, p))) < 0) die(`the built ${p} does not occur whole in ${WEBUI.exe}; this checkout, or the Node and npm it was built with, is not what that server was built from`);
  }
  const runs = readFileSync(listPath, 'utf8').trim().split('\n').map((l) => JSON.parse(l));
  rmSync(listPath, { force: true });
  const client = runs.filter((x) => !x.ssr);
  if (client.length !== 1) die(`expected one client build, found ${client.length}`);
  // every module with code in the page maps to a package directory, or to the page's own
  // sources; a module that maps to neither fails the run
  const slash = (s) => s.replace(/\\/g, '/');
  const uiS = slash(ui) + '/';
  const dirs = new Map();
  const add = (d, why) => { if (!dirs.has(d)) dirs.set(d, new Set()); dirs.get(d).add(why); };
  const pkgDir = (id) => {
    const s = slash(id).replace(/\?.*$/, '');
    const i = s.lastIndexOf('/node_modules/');
    const rest = s.slice(i + 14).split('/');
    return s.slice(0, i) + '/node_modules/' + (rest[0].startsWith('@') ? `${rest[0]}/${rest[1]}` : rest[0]);
  };
  const unknown = [];
  for (const mods of Object.values(client[0].out)) for (const [id, len] of Object.entries(mods || {})) {
    if (!len) continue;
    if (slash(id).includes('/node_modules/')) add(pkgDir(id.replace(/^\0/, '')), 'code'); // a package's module, or the bundler's CommonJS wrapper of one
    else if (id.startsWith('\0')) {
      if (/^\0(vite\/|commonjsHelpers)/.test(id)) add(uiS + 'node_modules/vite', 'bundler');
      else if (/^\0virtual:__sveltekit\//.test(id)) add(uiS + 'node_modules/@sveltejs/kit', 'code');
      else unknown.push(id.slice(1));
    } else if (slash(id).startsWith(uiS + 'src/')) continue;
    else if (slash(id).startsWith(uiS + '.svelte-kit/generated/')) add(uiS + 'node_modules/@sveltejs/kit', 'code');
    else unknown.push(slash(id));
  }
  if (unknown.length) die(`modules with code in the page that are neither a package's nor tools/ui/src's:\n  ${unknown.join('\n  ')}`);
  for (const w of client[0].watch.map(slash)) if (w.includes('/node_modules/') && /\.(css|scss|sass|less|woff2?|ttf|otf|eot)$/i.test(w)) add(pkgDir(w), 'style');
  const byKey = new Map();
  for (const [d, why] of dirs) {
    const pj = JSON.parse(readFileSync(join(d, 'package.json'), 'utf8'));
    const key = `${pj.name} ${pj.version}`;
    if (byKey.has(key)) continue;
    byKey.set(key, {
      name: pj.name, version: pj.version, license: typeof pj.license === 'string' ? pj.license : pj.license?.type,
      repository: typeof pj.repository === 'string' ? pj.repository : pj.repository?.url, authors: typeof pj.author === 'string' ? pj.author : pj.author?.name,
      texts: licenceTexts(d),
      note: why.has('bundler') && !why.has('code') ? 'the bundler: listed because its build adds modules of its own to bundle.js,\n    a module-preload helper and CommonJS helpers' : !why.has('code') ? 'no code in bundle.js; bundle.css was built from its style or font files' : undefined,
    });
  }
  const items = [...byKey.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version, undefined, { numeric: true }));
  const lockSha = createHash('sha256').update(readFileSync(join(ui, 'package-lock.json'))).digest('hex');
  const exeSha = createHash('sha256').update(exe).digest('hex');
  writeFileSync(join(ROOT, WEBUI.file), renderDeps('package', 'npm packages in the web page llama-server.exe carries',
    `llama-server.exe carries a web page, index.html, bundle.js, bundle.css and\nloading.html, built from llama.cpp's tools/ui. Listed: every package whose\ncode the build kept in bundle.js, every package bundle.css was built from a\nstyle or font file of, and the bundler, whose own helper modules are in\nbundle.js. Each line gives the package's name, version and licence field,\nthen the licence files it ships, by the number of the text below.`, items,
    `Generated by \`node tools/derive-notice.mjs --webui <llama.cpp checkout>\` from\ntools/ui at llama.cpp commit ${commit},\nwhose package-lock.json has sha256\n${lockSha},\nbuilt with Node ${process.version}. Each of the four files that build wrote occurs\nwhole in the server this file describes,\nllama-server.exe (sha256 ${exeSha}),\nand a check fails when the llama-server.exe beside it differs. Line endings\nare written as LF; the words are the files' own.`));
  recordSha([WEBUI.file.slice('licenses/'.length)], '--webui');
  console.log(`--webui: wrote ${WEBUI.file} (${items.length} packages, from commit ${commit.slice(0, 9)})`);
}

// ── inventory ────────────────────────────────────────────────────────────────
const SKIP_DIR = new Set(['node_modules', 'target', 'dist', '.git', '.vite', 'raw', 'out']);
function walkDisk(dir, acc, rel = '') {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const r = rel ? `${rel}/${name}` : name;
    const st = statSync(p);
    if (st.isDirectory()) { if (!SKIP_DIR.has(name)) walkDisk(p, acc, r); }
    else if (!/\.log$/.test(name)) acc.push(r);
  }
  return acc;
}
const files = isGit
  ? execFileSync('git', ['-C', ROOT, 'ls-files', '-z', '--cached', '--others', '--exclude-standard'], { encoding: 'utf8' }).split('\0').filter(Boolean)
  : walkDisk(ROOT, []).sort();
const fileSet = new Set(files);
const under = (dir) => files.filter((f) => f.startsWith(dir + '/'));
const fail = [];

// ── the components: what third-party material can be in a tree, and its line ─────
// detect: which files are this component's; license: the license text that must sit in the
// tree beside them (checked); line(found): the NOTICE bullet, written from what was found.
const dirsOf = (list) => [...new Set(list.map((f) => f.slice(0, f.lastIndexOf('/'))))];
// the llama folder's Microsoft files (the Visual C++ runtime) and its OpenMP runtime
const MS_CRT = /^(msvcp140|vcruntime140|vcruntime140_1)\.dll$/i;
const OMP_RE = /(^|\/)libomp140\.x86_64\.dll$/i;
const OMP_LICENSE = 'licenses/llvm-openmp-LICENSE.txt';
// the sha256 of the libomp140.x86_64.dll in llama.cpp's b9222 zip: Microsoft's build, from a
// Visual Studio folder Microsoft does not allow to be distributed (licenses/msvc-runtime.txt)
const OMP_MICROSOFT = '9ab1cb787e52b2a36133899c01c1db1f876067d1471cd224ead85f40a8152b99';
const COMPONENTS = [
  {
    name: 'IBM Plex', detect: /^(site\/assets\/fonts|app\/frontend\/public\/fonts)\/IBMPlex.*\.woff2$/,
    license: (found) => dirsOf(found).map((d) => `${d}/LICENSE.txt`),
    line: (found) => `- IBM Plex (IBM Corp., Reserved Font Name "Plex"): SIL Open Font License\n  1.1. Latin woff2 subsets (${found.length} files) in ${dirsOf(found).map((d) => d + '/').join(' and\n  ')}; the full OFL text ships in each directory as LICENSE.txt.`,
  },
  {
    name: 'Adobe CMaps', detect: /^app\/frontend\/public\/pdfjs\/cmaps\/.*\.bcmap$/,
    license: () => ['app/frontend/public/pdfjs/cmaps/LICENSE'],
    line: (found) => `- Adobe CMap resources (Adobe Systems Incorporated): BSD-3-Clause.\n  app/frontend/public/pdfjs/cmaps/ (${found.length} .bcmap files) — see cmaps/LICENSE.`,
  },
  {
    name: 'Foxit fonts', detect: /^app\/frontend\/public\/pdfjs\/standard_fonts\/Foxit.*\.pfb$/,
    license: () => ['app/frontend/public/pdfjs/standard_fonts/LICENSE_FOXIT'],
    line: (found) => `- Foxit base-14 substitute fonts (PDFium Authors): BSD-3-Clause.\n  app/frontend/public/pdfjs/standard_fonts/ (${found.length} .pfb files) — see LICENSE_FOXIT.`,
  },
  {
    name: 'Liberation fonts', detect: /^app\/frontend\/public\/pdfjs\/standard_fonts\/Liberation.*\.ttf$/,
    license: () => ['app/frontend/public/pdfjs/standard_fonts/LICENSE_LIBERATION'],
    line: (found) => `- Liberation fonts (Red Hat, Inc.; digitized data Google Corporation):\n  SIL Open Font License 1.1.\n  app/frontend/public/pdfjs/standard_fonts/ (${found.length} .ttf files) — see LICENSE_LIBERATION.`,
  },
  {
    name: 'Tesseract language data', detect: /(^|\/)[a-z_]+\.traineddata$/,
    license: () => [],
    line: (found) => `- Tesseract language data (tesseract-ocr authors): Apache-2.0.\n  ${found.join(', ')}.`,
  },
  {
    name: 'Caselaw Access Project opinions', detect: /^(corpus|newcases|app\/frontend\/public\/cases)\/.*\.txt$/,
    license: () => [],
    line: (found) => `- Caselaw Access Project opinions (${found.length} files): public domain.\n  ${dirsOf(found).map((d) => d + '/').join(', ')}.`,
  },
  {
    name: 'llama.cpp', detect: /^(llama-cuda|llama)\/(llama-server\.exe|.*\.dll)$/,
    license: (found) => [...dirsOf(found).map((d) => `${d}/LICENSE`), ...(found.some((f) => OMP_RE.test(f)) ? [OMP_LICENSE] : [])],
    // libomp140.x86_64.dll was said here to be "Apache-2.0 with LLVM exceptions" until
    // 2026-09-25, when the copy that shipped was Microsoft's build (signed by Microsoft,
    // byte-identical to Visual Studio's debug_nonredist copy), which carries no such licence.
    // By owner ruling the same day, the copy that ships is the LLVM project's own OpenMP
    // runtime from conda-forge's llvm-openmp 22.1.8 (tools/fetch-deps.mjs, OMP), which is under
    // Apache-2.0 with LLVM exceptions; a check below refuses Microsoft's copy. Until the same
    // day this line also called the folder "a stock Windows Vulkan release build". Neither the
    // OpenMP runtime nor the three Visual C++ runtime files come from llama.cpp's release zip,
    // so they are counted apart.
    line: (found) => {
      const crt = found.filter((f) => MS_CRT.test(f.slice(f.lastIndexOf('/') + 1)));
      const omp = found.filter((f) => OMP_RE.test(f));
      return `- llama.cpp / llama-server (The ggml authors): MIT. ${dirsOf(found).map((d) => d + '/').join(', ')} —\n  llama-server.exe and ${found.length - 1 - crt.length - omp.length} DLLs from llama.cpp's Windows Vulkan release\n  zip. License text: ${dirsOf(found).map((d) => d + '/LICENSE').join(', ')}.${omp.length ? ` Beside them:\n  libomp140.x86_64.dll, the LLVM project's OpenMP runtime as conda-forge builds\n  it (llvm-openmp 22.1.8): Apache-2.0 with LLVM exceptions, license text\n  ${OMP_LICENSE}.` : ''} Also beside them: ${crt.length} Visual C++\n  runtime files (msvcp140, vcruntime140, vcruntime140_1), Microsoft's, taken\n  from Visual Studio 2022 Build Tools. What is known of their terms is in\n  licenses/msvc-runtime.txt.`;
    },
  },
  {
    name: 'Node.js', detect: /^app\/src-tauri\/binaries\/node-.*\.exe$/,
    license: () => ['app/src-tauri/binaries/LICENSE-node.txt'],
    line: (found) => `- Node.js (Node.js contributors; OpenJS Foundation): MIT, with the licenses of\n  the components it bundles (V8, OpenSSL, ICU, zlib, libuv, …) in the same file.\n  ${found.join(', ')} — the runtime the app\n  starts the frozen engine with. License text: app/src-tauri/binaries/LICENSE-node.txt.`,
  },
];
// material that must NOT be in any tree
const FORBIDDEN = [
  [/\.gguf$/, 'Gemma model weights'],
  [/^raw\//, 'the lab bench (raw/)'],
  [/^pii-bench\/withheld\//, 'withheld annotations'],
  [/(^|\/)(sg-judgment-|sg-r\d-|sghcf-r\d-).*\.txt$|\.elitigation\.htm$/, 'a Singapore judgment'],
  [/^_serve\//, 'adapter scratch'],
];
// files that look third-party (binary formats) — each must belong to a component
const BINARY_RE = /\.(exe|dll|so|dylib|woff2?|ttf|otf|pfb|bcmap|traineddata|wasm|node|gguf|bin|zip|jar)$/i;

// ── software fetched at build time: every dependency needs a license line ──────
const NPM_LICENSE = {
  'pdfjs-dist': 'Apache-2.0 (Mozilla Foundation)',
  'fast-xml-parser': 'MIT',
  react: 'MIT (Meta Platforms)', 'react-dom': 'MIT (Meta Platforms)',
  '@tauri-apps/api': 'MIT or Apache-2.0 (Tauri Programme within The Commons Conservancy)',
  '@tauri-apps/plugin-dialog': 'MIT or Apache-2.0 (Tauri Programme within The Commons Conservancy)',
  'tesseract.js': 'Apache-2.0',
};
const CRATE_LICENSE = {
  tauri: 'MIT or Apache-2.0', 'tauri-build': 'MIT or Apache-2.0', 'tauri-plugin-dialog': 'MIT or Apache-2.0',
  serde: 'MIT or Apache-2.0', serde_json: 'MIT or Apache-2.0', sha2: 'MIT or Apache-2.0 (RustCrypto)',
  ureq: 'MIT or Apache-2.0', windows: 'MIT or Apache-2.0 (Microsoft)',
};
const software = [];
for (const pj of files.filter((f) => /(^|\/)package\.json$/.test(f) && !f.includes('node_modules'))) {
  const j = JSON.parse(readFileSync(join(ROOT, pj), 'utf8'));
  for (const dep of Object.keys(j.dependencies || {})) {
    const lic = NPM_LICENSE[dep];
    if (!lic) { fail.push(`${pj}: dependency "${dep}" has no license line in tools/derive-notice.mjs`); continue; }
    software.push(`- ${dep} (npm, ${dirname(pj) || '.'}): ${lic}.`);
  }
}
for (const ct of files.filter((f) => /(^|\/)Cargo\.toml$/.test(f))) {
  const text = readFileSync(join(ROOT, ct), 'utf8');
  let inDeps = false;
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (/^\[/.test(line)) { inDeps = /dependencies\]$/.test(line); continue; }
    const m = inDeps && /^([A-Za-z0-9_-]+)\s*=/.exec(line);
    if (!m) continue;
    const lic = CRATE_LICENSE[m[1]];
    if (!lic) { fail.push(`${ct}: crate "${m[1]}" has no license line in tools/derive-notice.mjs`); continue; }
    software.push(`- ${m[1]} (crate, ${dirname(ct)}): ${lic}.`);
  }
}

// ── classify every file ─────────────────────────────────────────────────────
const found = new Map(COMPONENTS.map((c) => [c.name, []]));
for (const f of files) {
  for (const [re, what] of FORBIDDEN) if (re.test(f)) fail.push(`forbidden material in the tree: ${f} (${what})`);
  const owners = COMPONENTS.filter((c) => c.detect.test(f));
  if (owners.length > 1) fail.push(`${f} matches more than one component: ${owners.map((c) => c.name).join(', ')}`);
  if (owners.length) found.get(owners[0].name).push(f);
  else if (BINARY_RE.test(f)) fail.push(`third-party-looking file has no NOTICE line: ${f}`);
}
const present = COMPONENTS.filter((c) => found.get(c.name).length);
for (const c of present) for (const lic of c.license(found.get(c.name))) if (!fileSet.has(lic)) fail.push(`${c.name}: license text missing from the tree: ${lic}`);

// ── what the Windows installer carries (read from app/src-tauri/tauri.conf.json) ──────
// The installer carries files a clone does not: the llama.cpp build (gitignored llama-cuda/)
// and the Node runtime (gitignored app/src-tauri/binaries/). Their licence texts are tracked
// in licenses/, which the installer carries beside the app with LICENSE, NOTICE and
// THIRD_PARTY_NOTICES.md; its licence page shows LICENSE, then the section on Microsoft's
// files (checked below, with its CONTROLs). Checked here: the configuration
// still says all of that; every bundled path the inventory does not carry has its texts
// listed below and present; every file in licenses/ is listed in licenses/README.md with the
// sha256 of its bytes, and nothing there is unlisted.
const CONF = 'app/src-tauri/tauri.conf.json';
const LIC_README = 'licenses/README.md';
const PAYLOAD = {
  'llama-cuda/': {
    texts: ['licenses/llama.cpp-LICENSE.txt', 'licenses/llama.cpp-jsonhpp-LICENSE.txt', 'licenses/llama.cpp-cpp-httplib-LICENSE.txt', 'licenses/llama.cpp-BoringSSL-LICENSE.txt', WEBUI.file, OMP_LICENSE, 'licenses/msvc-runtime.txt'],
    line: `- llama.cpp (llama-server and its libraries, from llama.cpp's Windows release\n  zip; The ggml authors), installed as llama\\: MIT\n  (licenses/llama.cpp-LICENSE.txt), with the licences of code compiled into\n  it: nlohmann/json and cpp-httplib (MIT) and BoringSSL\n  (licenses/llama.cpp-*-LICENSE.txt), and of the npm packages in the web page\n  llama-server.exe carries (${WEBUI.file}).\n  Beside it: libomp140.x86_64.dll, the LLVM project's OpenMP runtime as\n  conda-forge builds it (llvm-openmp 22.1.8), Apache-2.0 with LLVM exceptions\n  (${OMP_LICENSE}); and three files built by Microsoft, the\n  Visual C++ runtime, added from Visual Studio 2022 Build Tools, which come\n  with no licence text. licenses/msvc-runtime.txt says where they come from\n  and quotes what Microsoft says about redistributing them.`,
  },
  'app/src-tauri/binaries/node': {
    texts: ['licenses/node-LICENSE.txt'],
    line: `- Node.js (Node.js contributors; OpenJS Foundation), installed as node.exe:\n  MIT, with the licences of the components it includes\n  (licenses/node-LICENSE.txt).`,
  },
};
const sha256 = (p) => createHash('sha256').update(readFileSync(join(ROOT, p))).digest('hex');
const installer = { conf: fileSet.has(CONF), payloads: [] };
if (installer.conf) {
  const b = JSON.parse(readFileSync(join(ROOT, CONF), 'utf8')).bundle || {};
  const fromConf = (p) => relative(ROOT, resolve(ROOT, 'app/src-tauri', p)).replace(/\\/g, '/') + (/[\\/]$/.test(p) ? '/' : '');
  // the licence page: LICENSE's bytes, then the section on Microsoft's files (below)
  const pageRel = typeof b.licenseFile === 'string' ? fromConf(b.licenseFile) : null;
  const bytesOf = (rel) => (rel && fileSet.has(rel) ? readFileSync(join(ROOT, rel)) : null);
  installer.page = { rel: pageRel, bytes: bytesOf(pageRel), license: bytesOf('LICENSE') };
  if (b.license !== 'Apache-2.0') fail.push(`${CONF}: bundle.license is ${JSON.stringify(b.license ?? null)}, not "Apache-2.0"`);
  const res = Array.isArray(b.resources) ? b.resources : Object.keys(b.resources || {});
  const sources = res.map(fromConf);
  for (const need of ['LICENSE', 'NOTICE', 'THIRD_PARTY_NOTICES.md', 'licenses/']) if (!sources.includes(need)) fail.push(`${CONF}: bundle.resources no longer carries ${need} into the installer`);
  for (const src of [...sources, ...(b.externalBin || []).map(fromConf)]) {
    if (PAYLOAD[src]) { installer.payloads.push(src); continue; }
    if (src === 'NOTICE') continue; // this run derives it; its absence fails below
    const carried = src.endsWith('/') ? files.some((f) => f.startsWith(src)) : fileSet.has(src);
    if (!carried) fail.push(`${CONF}: the installer bundles ${src}, which this tree does not carry and which has no licence texts in tools/derive-notice.mjs PAYLOAD`);
  }
  for (const src of installer.payloads) for (const t of PAYLOAD[src].texts) if (!fileSet.has(t)) fail.push(`the installer bundles ${src}; its licence text ${t} is missing`);
}

// ── the installer's licence page (owner rulings of 2026-09-25) ────────────────────
// The product is Apache-2.0 with no end-user licence of its own (ruling 28), and LICENSE stays
// the plain Apache-2.0 text, which is what GitHub's licence detection reads. Microsoft's terms
// for the Visual C++ runtime in the llama folder require the distributor to "require
// distributors and external end users to agree to terms that protect the Distributable Code
// at least as much as this agreement" (licenses/msvc-runtime.txt). So the page the installer
// shows (bundle.licenseFile) is LICENSE, byte for byte, followed by one section on those
// files, which the user accepts with the page's I Agree. NSIS shows the file as it is: LICENSE
// is LF-only, so the section is LF-only and plain ASCII too.
// The check fails when the page is not that file, does not begin with LICENSE's exact bytes,
// or has a section that names a file the llama folder does not hold, names one that is not
// Microsoft's, or leaves one of Microsoft's out. Its CONTROLs are run on every check.
const LICENCE_PAGE = 'app/src-tauri/installer-licence.txt';
const PAGE_HEADING = 'Microsoft Visual C++ runtime files in the llama folder';
// The llama folder's files and which of them are Microsoft's: the pins in tools/fetch-deps.mjs
// where this tree has it (a clone), else the folder on disk (the distribution tree, which
// carries llama-cuda/ and not fetch-deps.mjs).
function llamaFolder() {
  if (fileSet.has('tools/fetch-deps.mjs')) {
    const src = readFileSync(join(ROOT, 'tools/fetch-deps.mjs'), 'utf8');
    const pins = (s) => [...s.matchAll(/\[\s*'([^'/]+)',\s*'[0-9a-f]{64}',\s*\d+\s*\]/g)].map((m) => m[1]);
    const vcrt = /^const VCRT = \{[\s\S]*?^\};/m.exec(src);
    return { from: 'the files tools/fetch-deps.mjs pins for llama-cuda/', all: pins(src), microsoft: vcrt ? pins(vcrt[0]) : [] };
  }
  if (existsSync(join(ROOT, 'llama-cuda'))) {
    const all = readdirSync(join(ROOT, 'llama-cuda'));
    return { from: 'llama-cuda/', all, microsoft: all.filter((n) => MS_CRT.test(n)) };
  }
  return null;
}
function licencePageProblems(rel, page, license, folder) {
  const out = [];
  if (rel !== LICENCE_PAGE) out.push(`${CONF}: bundle.licenseFile must name ${LICENCE_PAGE} ("installer-licence.txt"), the page the installer's licence screen shows; it names ${rel ?? 'nothing'}`);
  if (!page) { out.push(`${rel ?? LICENCE_PAGE} is not in this tree`); return out; }
  if (!license) { out.push('LICENSE is not in this tree'); return out; }
  if (page.length < license.length || !page.subarray(0, license.length).equals(license)) {
    let i = 0;
    while (i < license.length && page[i] === license[i]) i++;
    out.push(`${rel} does not begin with LICENSE's exact bytes (the first difference is at byte ${i})`);
  }
  const section = page.subarray(license.length).toString('latin1');
  if (!section.includes(PAGE_HEADING)) out.push(`${rel} has no section headed "${PAGE_HEADING}" after LICENSE`);
  if (/[^\t\n\r\x20-\x7e]/.test(section)) out.push(`the section after LICENSE in ${rel} is not plain ASCII`);
  if (license.includes(13) ? /(^|[^\r])\n/.test(section) : section.includes('\r')) out.push(`the section after LICENSE in ${rel} does not use LICENSE's line endings (${license.includes(13) ? 'CRLF' : 'LF'}); NSIS shows the file as it is`);
  if (!/licenses[\\/]msvc-runtime\.txt/.test(section)) out.push(`the section after LICENSE in ${rel} does not say where Microsoft's terms are (licenses\\msvc-runtime.txt)`);
  if (!folder) { out.push('no list of the llama folder to check the section against: this tree has neither tools/fetch-deps.mjs nor llama-cuda/'); return out; }
  if (!folder.microsoft.length) out.push(`${folder.from} names no Microsoft file to check the section against`);
  const named = [...new Set([...section.matchAll(/[A-Za-z0-9_.-]+\.dll\b/gi)].map((m) => m[0]))];
  for (const n of named) {
    if (!folder.all.some((f) => f.toLowerCase() === n.toLowerCase())) out.push(`the section after LICENSE in ${rel} names ${n}, which is not in the llama folder (${folder.from})`);
    else if (!folder.microsoft.some((f) => f.toLowerCase() === n.toLowerCase())) out.push(`the section after LICENSE in ${rel} names ${n} as Microsoft's; the llama folder's Microsoft files are ${folder.microsoft.join(', ')}`);
  }
  for (const m of folder.microsoft) if (!named.some((n) => n.toLowerCase() === m.toLowerCase())) out.push(`the section after LICENSE in ${rel} leaves out ${m}, a Microsoft file in the llama folder`);
  return out;
}
const pageChecks = { problems: 0, controls: 0 };
if (installer.conf) {
  const { rel, bytes, license } = installer.page;
  const folder = llamaFolder();
  const problems = licencePageProblems(rel, bytes, license, folder);
  for (const p of problems) fail.push(p);
  pageChecks.problems = problems.length;
  // CONTROLs: each breaks the page one way, and the check must fail on it
  const edit = (from, to) => () => {
    const s = bytes.toString('latin1');
    if (!s.includes(from)) throw new Error(`the page has no "${from}" to change`);
    return [rel, Buffer.from(s.replace(from, to), 'latin1'), license, folder];
  };
  const CONTROLS = [
    ['the licence page set back to LICENSE', () => ['LICENSE', license, license, folder]],
    ['LICENSE\'s line ends turned to CRLF on the page', () => [rel, Buffer.concat([Buffer.from(license.toString('latin1').replace(/\n/g, '\r\n'), 'latin1'), bytes.subarray(license.length)]), license, folder]],
    ['one word of the Apache text changed on the page', edit('Apache License', 'Apache Licence')],
    ['the section naming vcomp140.dll, which is not in the llama folder', edit('msvcp140.dll, ', 'msvcp140.dll, vcomp140.dll, ')],
    ['the section calling libomp140.x86_64.dll Microsoft\'s', edit('msvcp140.dll, ', 'msvcp140.dll, libomp140.x86_64.dll, ')],
    ['the section without vcruntime140_1.dll', edit(' and vcruntime140_1.dll', '')],
    ['the section without its pointer to Microsoft\'s terms', edit('licenses\\msvc-runtime.txt', 'the licenses folder')],
    ['the section with a CRLF line', edit(`${PAGE_HEADING}\n`, `${PAGE_HEADING}\r\n`)],
  ];
  if (bytes && license && !problems.length) {
    for (const [name, make] of CONTROLS) {
      let caught;
      try { caught = licencePageProblems(...make()).length > 0; } catch (e) { fail.push(`licence page CONTROL (${name}) could not be built: ${e.message}`); continue; }
      if (!caught) fail.push(`licence page CONTROL (${name}) passed: the check cannot see it`);
      else pageChecks.controls++;
    }
    pageChecks.of = CONTROLS.length;
  }
}
// the OpenMP runtime the installer carries must not be Microsoft's build (the llama folder on
// this computer, or the distribution tree's)
if (existsSync(join(ROOT, 'llama-cuda', 'libomp140.x86_64.dll')) && sha256('llama-cuda/libomp140.x86_64.dll') === OMP_MICROSOFT) {
  fail.push(`llama-cuda/libomp140.x86_64.dll is Microsoft's build (sha256 ${OMP_MICROSOFT}), which may not be redistributed (licenses/msvc-runtime.txt, section 2); move it aside and run node tools/fetch-deps.mjs`);
}
const licFiles = under('licenses').filter((f) => f !== LIC_README);
if (installer.conf || licFiles.length) {
  if (!fileSet.has(LIC_README)) fail.push(`${LIC_README} is missing: it records the source and sha256 of every file in licenses/`);
  else {
    const listed = new Map([...readFileSync(join(ROOT, LIC_README), 'utf8').matchAll(/^\| `([^`/]+)` \|.*\| `([0-9a-f]{64})` \|\s*$/gm)].map((m) => [m[1], m[2]]));
    for (const f of licFiles) {
      const name = f.slice('licenses/'.length);
      if (!listed.has(name)) { fail.push(`${f} is not listed in ${LIC_README}`); continue; }
      const h = sha256(f);
      if (h !== listed.get(name)) fail.push(`${f}: its sha256 is ${h}; ${LIC_README} records ${listed.get(name)}`);
    }
    for (const name of listed.keys()) if (!fileSet.has(`licenses/${name}`)) fail.push(`${LIC_README} lists ${name}, which is not in licenses/`);
  }
}
// the compiled-in dependencies: when the installer builds from a lockfile in this tree, the
// licence file for it must exist and must have been written from that lockfile as it is now
const depFiles = [];
if (installer.conf) for (const { file, lock } of Object.values(DEP)) {
  if (!fileSet.has(lock)) continue;
  if (!fileSet.has(file)) { fail.push(`${file} is missing: the installer's app is built from ${lock} (run node tools/derive-notice.mjs --deps)`); continue; }
  depFiles.push(file);
  const rec = readFileSync(join(ROOT, file), 'utf8').match(/\(sha256 ([0-9a-f]{64})\)/);
  const now = sha256(lock);
  if (!rec || rec[1] !== now) fail.push(`${file} was written from a different ${lock} (recorded ${rec ? rec[1] : 'nothing'}, now ${now}); run node tools/derive-notice.mjs --deps`);
}
// the web page's licence file was written for one llama-server.exe; when a server is beside
// this tree (the build machine's gitignored llama-cuda/, or the distribution tree), it must be that one
if (fileSet.has(WEBUI.file)) {
  const rec = readFileSync(join(ROOT, WEBUI.file), 'utf8').match(/llama-server\.exe \(sha256 ([0-9a-f]{64})\)/);
  if (!rec) fail.push(`${WEBUI.file} records no llama-server.exe sha256; run node tools/derive-notice.mjs --webui <llama.cpp checkout>`);
  else if (existsSync(join(ROOT, WEBUI.exe)) && sha256(WEBUI.exe) !== rec[1]) fail.push(`${WEBUI.exe} is not the server ${WEBUI.file} was written for (recorded ${rec[1]}, now ${sha256(WEBUI.exe)}); run node tools/derive-notice.mjs --webui <llama.cpp checkout at that server's commit>`);
}
// a generated licence file that names another file in licenses/ (a crate's prebuilt library)
for (const f of [...depFiles, WEBUI.file].filter((x) => fileSet.has(x))) {
  for (const m of readFileSync(join(ROOT, f), 'utf8').matchAll(/(?<![\w/.:-])licenses\/[A-Za-z0-9_.-]+\.txt\b/g)) if (!fileSet.has(m[0])) fail.push(`${f} names ${m[0]}, which is not in licenses/`);
}
const wv2 = 'licenses/Microsoft.Web.WebView2-LICENSE.txt';

// ── the derived NOTICE ──────────────────────────────────────────────────────
const kind = isGit ? 'repository' : 'distribution tree';
const notice = `Simpler Legal
Copyright 2026 Simpler Terminal Value Systems Pte Ltd

Simpler Legal is made by Simpler Terminal Value Systems Pte Ltd, Singapore
(https://github.com/Simpler-Systems/simpler-legal; support@simpler.asia).
Licensed under the Apache License, Version 2.0.

Third-party software, fonts, data and models retain their own terms. This
file is derived from the contents of this ${kind} by tools/derive-notice.mjs
(inventory: ${isGit ? 'git ls-files' : 'every file in the tree'}); the fuller accounting is in
THIRD_PARTY_NOTICES.md.

Software fetched at build time (npm and crates.io; not vendored here)
${software.join('\n')}

${present.length ? `Third-party files that DO ship in this ${kind}\n${present.map((c) => c.line(found.get(c.name))).join('\n')}` : `No third-party file ships in this ${kind}.`}
${installer.conf ? `
The Windows installer built from this ${kind} (${CONF})
shows LICENSE on its licence page, followed by the terms Microsoft requires
users to accept for the three Visual C++ runtime files in its llama folder
(${LICENCE_PAGE}), and installs LICENSE, NOTICE,
THIRD_PARTY_NOTICES.md and the files in licenses/ into a licenses folder
beside the app.${installer.payloads.length ? ` Besides this
product's own files it carries the following (licenses/README.md gives the
source and sha256 of each file named):
${installer.payloads.map((s) => PAYLOAD[s].line).join('\n')}` : ''}${fileSet.has('licenses/NSIS-COPYING.txt') ? `
The setup program itself is built from NSIS 3.11 (licenses/NSIS-COPYING.txt)
and Tauri's nsis_tauri_utils.dll (licenses/nsis_tauri_utils-LICENSE_*.txt).` : ''}${depFiles.length ? `
The licence texts of the Rust crates linked into the app, and of the npm
packages its window is bundled from, are in
${depFiles.join(' and ')}.` : ''}${fileSet.has(wv2) ? `
The app's executable also links Microsoft's WebView2 loader
(WebView2LoaderStatic.lib, through the webview2-com-sys crate):
${wv2}, with the notices file of the package it comes
from, ${wv2.replace('LICENSE', 'NOTICE')}.` : ''}
` : ''}
Models and corpora that do NOT ship here (checked: none of these is in the tree)
- Gemma 4 E2B model weights (Google): Apache-2.0, per the model card and
  https://ai.google.dev/gemma/docs/gemma_4_license. Not redistributed:
  hash-pinned and located at runtime; never a repository or installer asset.
- TAB (Text Anonymization Benchmark), Norsk Regnesentral: MIT. Fetched
  at a pinned commit by ${isGit ? '' : "the development repository's "}build-pii-bench.mjs into raw/, which is not here.
- SEC EDGAR filings: US government public records. Fetched from
  sec.gov; documents not redistributed.
- Singapore eLitigation judgments: not redistributed; URLs and our
  annotations only.
- UK judgments from The National Archives' Find Case Law: Open Justice
  Licence; not redistributed, refetched by ${isGit ? '' : "the development repository's "}build-ukprobe.mjs with
  per-document attribution retained.
`;

const noticePath = join(ROOT, 'NOTICE');
if (WRITE) writeFileSync(noticePath, notice);
const onDisk = existsSync(noticePath) ? readFileSync(noticePath, 'utf8') : null;
if (onDisk === null) fail.push('NOTICE is missing (run with --write)');
else if (onDisk !== notice) {
  const a = onDisk.split('\n'), b = notice.split('\n');
  const first = a.findIndex((l, i) => l !== b[i]);
  fail.push(`NOTICE on disk differs from the derived one (first difference at line ${first + 1}:\n    disk:    ${JSON.stringify(a[first] ?? '')}\n    derived: ${JSON.stringify(b[first] ?? '')})\n  run with --write to replace it`);
}

// ── THIRD_PARTY_NOTICES.md: every path it names exists; every count it states is right ──
const tpnPath = join(ROOT, 'THIRD_PARTY_NOTICES.md');
if (!existsSync(tpnPath)) fail.push('THIRD_PARTY_NOTICES.md is missing');
else {
  const tpn = readFileSync(tpnPath, 'utf8');
  // every backticked string with a slash is a path claim: it must resolve in the tree, from
  // the root or as a suffix (a table row under a "Vendored under <dir>" heading). Paths under
  // raw/, out/, _serve/ and node_modules/ are named as NOT being in a clone — skipped.
  const claims = new Set();
  for (const m of tpn.matchAll(/`([^`\n]+)`/g)) {
    const c = m[1];
    if (!/^[A-Za-z0-9_.\-]+(\/[A-Za-z0-9_.\-*]+)+\/?$/.test(c)) continue; // not a path
    if (/^(raw|out|_serve|node_modules)\//.test(c)) continue;
    if (tpn.startsWith('](http', m.index + m[0].length)) continue; // a link to an upstream file, not a path here
    claims.add(c);
  }
  const esc = (s) => s.replace(/[.+^${}()|[\]\\]/g, '\\$&');
  for (const c of claims) {
    const re = new RegExp('(^|/)' + esc(c).replace(/\*/g, '[^/]*') + (c.endsWith('/') ? '' : '$'));
    const n = files.filter((f) => re.test(f)).length;
    if (!n) { fail.push(`THIRD_PARTY_NOTICES.md names ${c}, which is not in the tree`); continue; }
    if (!c.includes('*')) continue;
    // a count stated on the same table row must be the count in the tree
    const row = tpn.split('\n').find((l) => l.includes('`' + c + '`'));
    const cells = row ? row.split('|').map((s) => s.trim()) : [];
    const stated = cells.find((s) => /^\d+$/.test(s));
    if (stated && Number(stated) !== n) fail.push(`THIRD_PARTY_NOTICES.md says ${stated} files match ${c}; the tree has ${n}`);
  }
  for (const c of present) for (const lic of c.license(found.get(c.name))) if (!tpn.includes(lic.slice(lic.lastIndexOf('/') + 1))) fail.push(`THIRD_PARTY_NOTICES.md does not point at ${lic}`);
  for (const src of installer.payloads) for (const t of PAYLOAD[src].texts) if (!tpn.includes('`' + t + '`')) fail.push(`THIRD_PARTY_NOTICES.md does not point at ${t}, a licence text the installer carries`);
  for (const t of depFiles) if (!tpn.includes('`' + t + '`')) fail.push(`THIRD_PARTY_NOTICES.md does not point at ${t}, the licence texts of what the app is compiled from`);
  for (const t of [wv2, wv2.replace('LICENSE', 'NOTICE')]) if (fileSet.has(t) && !tpn.includes('`' + t + '`')) fail.push(`THIRD_PARTY_NOTICES.md does not point at ${t}, which covers a library linked into the app`);
}

console.log(`${kind} at ${ROOT} — ${files.length} files (${isGit ? 'git ls-files' : 'disk walk'})`);
for (const c of COMPONENTS) console.log(`  ${found.get(c.name).length ? '•' : '·'} ${c.name}: ${found.get(c.name).length} file(s)`);
console.log(`  software lines: ${software.length}`);
console.log(`  installer: ${installer.conf ? `${CONF} read; bundles ${installer.payloads.length ? installer.payloads.join(', ') : 'no third-party payload'}` : 'no installer configuration in this tree'}; licenses/ holds ${licFiles.length} text(s)`);
if (installer.conf) console.log(`  licence page: ${installer.page.rel ?? 'none'}; ${pageChecks.problems ? `${pageChecks.problems} problem(s)` : 'LICENSE byte for byte, then the section on Microsoft\'s files'}; ${pageChecks.of ? `${pageChecks.controls} of ${pageChecks.of} CONTROLs fail, as they must` : 'CONTROLs not run'}`);
if (fail.length) {
  console.error(`\nFAIL (${fail.length}):`);
  for (const f of fail) console.error('  - ' + f);
  process.exit(1);
}
console.log(WRITE ? 'NOTICE written; every check passed' : 'NOTICE matches the tree; every check passed');
