export default function About() {
  return (
    <section className="screen">
      <h1>About</h1>
      <div className="sub">Simpler Legal v0.1 — local redaction tuned for legal documents. Apache-2.0 licensed, © 2026 Simpler Terminal Value Systems Pte Ltd. The installer puts the licence, NOTICE and the third-party licence texts in a licenses folder beside the app, with a note on the Microsoft runtime files beside llama.cpp, which come with no licence text.</div>
      <div className="setcard">
        <div className="srow"><span className="k">Version</span><span>0.1.0 · legal pack pipeline (frozen v1-legal) via the local engine service, in-app core as fallback</span></div>
        <div className="srow"><span className="k">Network</span><span>The app downloads nothing, the model included: it finds the model file already on disk, and the launcher refuses one whose SHA-256 does not match the pin. Documents go only to 127.0.0.1. In the desktop app they go to the engine service once it proves it holds this launch's key, and to the model server once Windows says which process holds its port (another account's is refused), with each connection that carries text checked to reach that same process; a page opened in a plain browser cannot ask Windows who holds a port, so it uses the engine service only with that service's token and the model server unchecked, and Settings says so. The model server the desktop app starts gets its own key for each launch and its /slots page switched off, so a web page open on this computer can neither send it text nor read what it was last sent; the app checks that the server refuses a request without the key and that /slots cannot be read without it, and says so on screen if either check fails. While the key is in force the second check cannot tell a /slots page that is switched off from one that is only behind the key. Proxy settings in Windows' environment are removed from every process the app starts. An engine service started by hand refuses to run when Node is told to send its calls through a proxy (NODE_USE_ENV_PROXY or --use-env-proxy, with HTTP_PROXY set and 127.0.0.1 not in NO_PROXY); without that switch Node does not use the proxy settings</span></div>
        <div className="srow"><span className="k">Measured</span><span>46 unseen business documents across four consecutive fresh draws — zero DIRECT identity leaks in the redacted text (3 of the 46 carry no DIRECT span, so 43 had one to leak; round 4, the first draw under the current gold and scorer, leaked 3 in 1 of 15; published as drawn). Of the 46, rounds 5–7 ran the engine as it stood before the freeze and one document ran the frozen engine. Since then the frozen engine's output has been checked by hand on 20 public court filings in a law firm's shapes, not against sealed gold: no person on the hand list (individual parties and counsel included), no email and no phone left readable; 27 of its 296 identifiers were, in 14 of the 20 — party companies' names among them (in a caption, a Re: line, a settlement), a law firm's name, docket and case numbers, an address fragment and amounts. Judges and other public officials were not counted, and on papers it treats as court judgments the engine releases by design a name it reads as a judge's, or as counsel's on a counsel line ("…, for the plaintiff"), and the name of a court or public body acting officially ·<a href="/benchmark.html" target="_blank" rel="noreferrer">the full measurement record</a></span></div>
        <div className="srow"><span className="k">Made by</span><span>Simpler Terminal Value Systems Pte Ltd, Singapore · support@simpler.asia · Apache-2.0: free for anyone to use, change and pass on</span></div>
        <div className="srow"><span className="k">Source</span><span><span style={{ fontFamily: 'var(--mono)', fontSize: 12 }}>github.com/Simpler-Systems/simpler-legal</span> · security reports: the repository's Security tab (SECURITY.md), or support@simpler.asia, not a public issue · what the app sends and keeps: PRIVACY.md · verify us: turn off Wi-Fi and redact a document</span></div>
        <div className="postnote">The honest claim: we measure on real documents and publish what we find, including the misses. Every round board is committed; the firm-paper figures rest on a committed write-up whose filings and engine output are not in the repository, and one run of the frozen engine on 26 gov.uk files recorded no leak result. Not “provably perfect on any document ever written” — that's why you review the table before anything leaves.</div>
      </div>
    </section>
  );
}
